set encoding=utf-8
set autoread
set showcmd
set mouse=
set number
set cursorline
set wildignorecase

let mapleader=","
set timeoutlen=1000
set scrolloff=10
filetype plugin indent on
syntax enable

" search
set hlsearch
set incsearch
set ignorecase
set smartcase
set gdefault

" indent
set expandtab
set shiftwidth=4
set tabstop=4
set copyindent
set smarttab
set autoindent
set smartindent

" swap file storage
set backupdir=$HOME/.cache
set directory=$HOME/.cache

" paragraph nav
noremap J }
noremap K {

" join lines
noremap M J

" page nav
noremap { <C-f>
noremap } <C-b>

" BOL and EOL
noremap H ^
noremap ^ H
noremap L $
noremap $ L

" redo remap
nnoremap U <C-r>

" explorer/netrw
nnoremap <Leader>dd :Explore %:p:h<cr>
nnoremap <Leader>da :Explore<cr>
let g:netrw_keepdir = 0
let g:netrw_winsize = 20
let g:netrw_banner = 0
let g:netrw_fastbrowse = 0
let g:netrw_localcopydircmd = "cp -r"
